language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install git gfortran g++
  - sudo apt-get install libatlas-base-dev libblas-dev liblapack-dev

install:
   - "pip install . --use-mirrors"

script: nosetests
